server:
  port: 7002
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/saii
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE  
eureka:
  instance:
   prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka